### ISSUE TITLE
A few functions are outdated

### ISSUE THREAD

**Issue by mdogucu** [sjystu/tactileR#1]
Dear @jooyoungseo,

I thought I'd let you know of the following messages. 

When I use `brl_begin` I get the messages

>'font.add()' is now renamed to 'font_add()'
>The old version still works, but consider using the new function in future code

>'showtext.begin()' is now renamed to 'showtext_begin()'
>The old version still works, but consider using the new function in future code

When I use `brl_end` I get the messages

>'showtext.end()' is now renamed to 'showtext_end()'
>The old version still works, but consider using the new function in future code

**Comment by jooyoungseo** [comment]
Thanks for the report. Yes, this is the expected warning coming from showtext.
